### ISSUE TITLE
Consistency in the README.md

### ISSUE THREAD

**Issue by peter-murray** [npm/npm-package-arg#10]
The top most example in the README.md is not consistent with how this module works.

The @bar/foo@1.2 parsing shows an example where the returned object has a name property of 'foo', but the reality is that it will be '@bar/foo'.

**Comment by zeke** [comment]
Yep. Seeing this in `3.1.0`:

```
> require("npm-package-arg")("@bar/foo@1.2")
{ raw: '@bar/foo@1.2',
  scope: '@bar',
  name: '@bar/foo',
  rawSpec: '1.2',
  spec: '>=1.2.0 <1.3.0',
  type: 'range' }
```

Is this a bug in the code or the readme?

**Comment by iarna** [comment]
That's a good question…

**Comment by iarna** [comment]
Ok, so, I can confirm that's a bug in the documentation. The module has never worked that way, and I introduced the documentation much later on.

**Comment by iarna** [comment]
I've pushed 3.1.1 which fixes the documentation.

**Comment by zeke** [comment]
:cake:
