### ISSUE TITLE
What about an owner property, or an @-less value of scope?

### ISSUE THREAD

**Issue by zeke** [npm/npm-package-arg#13]
```js
npa("@bar/foo@1.2").scope === "@bar"
```

I just want the `bar` part, because that's the username I need to compare stuff to. I could just do `package.scope.replace(/^@/, '')` or whatever all over the place, but I don't like that. Would y'all be open to a change that added a property for this? Maybe `owner`?

OR... we could take `@` off the scope. That would be even better! Like this:

```js
{
  raw: '@bar/foo@1.2'
  name: "@bar/foo",
  scope: "bar",
  type: "range",
  spec: ">=1.2.0 <1.3.0"
  rawSpec: "1.2"
 }
```

**Comment by iarna** [comment]
Interestingly the earliest version of scope support did this.  I don't know why that was changed.

Changing this would require similar changes to npm (the caching code in particular I believe...)

So... adding another attribute is *easy* but...

**Comment by othiym23** [comment]
-1 on removing the `@` from the `scope` property. It's part of the scope name, as distinct from the owner, org, or team names which hang off the scopes. I'm +0 on adding a new attribute, mostly because it's pretty easy to write `const owner = package.scope.slice(1)`, but I can see how that would get repetitive.

**Comment by zeke** [comment]
Reopening, because I'm finding instances of `@<scope>` throughout the npm docs.

We should reconsider dropping the `@` from `npa(name).scope`, or update all this documentation:

![screen shot 2015-03-24 at 11 47 51 am](https://cloud.githubusercontent.com/assets/2289/6810087/c4ddfb9c-d21b-11e4-8a87-82de92621b5e.png)

**Comment by iarna** [comment]
I don't think end user orientated command line docs need imply anything about the shape of our APIs. So I don't see those docs using `@<scope>` as a compelling reason to consider changing library behavior or vice versa.

**Comment by zeke** [comment]
@smikes (or someone else?) went through all the docs a few weeks ago and fixed all the `@<scope>` references, so this is resolved.
