### ISSUE TITLE
Environment Variables in File Path

### ISSUE THREAD

**Issue by rrdelaney** [npm/npm-package-arg#16]
It would be really helpful if you could use environment variables when specifying a local dependency. All this involves is replacing the name of a variable in the `file:...` specifier. This is fairly easy to implement myself, but there are some questions I'd like to address before sending a PR:
1. What should the control sequence for the environment variable look like? I was thinking something like `$ENV_VAR/...` or `%ENV_VAR/...`. `$`, although common, could be problematic because it is a valid character in file paths on both Windows and Unix-like OS's. Using `%` solves the Windows problem, but still leaves it for Unix-likes.
2. How can this get merged into npm? This change breaks semver, meaning realize-package-specifier would also have to be updated before finally landing in npm.

**Comment by iarna** [comment]
I think it might be better to back up and talk about what problem you'd like to solve with this?

**Comment by rrdelaney** [comment]
I forgot about this 😱 Thanks for responding though!

The original idea was to have multiple packages interior with paths specified by an environment variable like "%PROJECT_ROOT%/my-package-2" and then "my-package-1" could use it as a mode module. 

Eventually what I did was put all my packages that needed to interop like that in a node_modules folder
