### ISSUE TITLE
Support for .git https urls 

### ISSUE THREAD

**Issue by mgcrea** [npm/npm-package-arg#19]
Currently: `https://apache.googlesource.com/cordova-cli.git` is detected as `type: 'remote'`.

It should be `type: 'git'`.

Would you accept a PR fixing this?

**Comment by iarna** [comment]
`https://apache.googlesource.com/cordova-cli.git` should be `git+https://apache.googlesource.com/cordova-cli.git` to be treated as git.

**Comment by mgcrea** [comment]
I agree, we can close this.
