### ISSUE TITLE
maybeGitHubShorthand should not return true for `../string` and `./string`

### ISSUE THREAD

**Issue by dylang** [npm/npm-package-arg#2]
Can we add `.` to the first negate pattern of `maybeGitHubShorthand`?

According to github: 

> Username may only contain alphanumeric characters or dashes and cannot begin with a dash

The same applies for github org names.

New code:
```js
function maybeGitHubShorthand(arg) {
  return /^[^.@ \/%]+\/[^@ \/%]+$/.test(arg)
}
```

(Repo names can start with `.`, such as [https://github.com/dylang/...](https://github.com/dylang/...), but I wouldn't recommend it.)

**Comment by iarna** [comment]
This was addressed by the addition of hosted-git-info. `../foo` now parses as local as it should.
