### ISSUE TITLE
Incorrect fetchSpec for git+https when using :user format

### ISSUE THREAD

**Issue by geej** [npm/npm-package-arg#28]
For example, ```git+https://git@notgithub.com:user/foo.git``` results in a fetchSpec of ```https://git@nothithub.com/:user/foo.git```

This was working in previous versions, and should resolve to ```https://git@nothithub.com/user/foo.git```

(PR: https://github.com/npm/npm-package-arg/pull/27)

**Comment by iarna** [comment]
`git+https://git@notgithub.com:user/foo.git` is not a valid URL, is the thing. (`user` is a port in your example) and I'm not sure how I feel about supporting that.  Rewriting it to `/:` isn't super great either though, mmm...

**Comment by defcc** [comment]
Maybe we could add a warning when installing ? @geej @iarna
