### ISSUE TITLE
[BUG] (CLI-related) Specifier without package name is parsed incorrectly

### ISSUE THREAD

**Issue by jameschensmith** [npm/npm-package-arg#55]
# What / Why

When using npm, the spec alone is passed to `npa`.  npm-package-arg is parsing the spec as the name of the package, which is an unintended result.

```js
const npa = require("npm-package-arg");
console.log(JSON.stringify(npa("~3.5.0"), undefined, 2));
// Expected (or, an estimation of what is expected):
// {
//   "type": "range",
//   "registry": true,
//   "raw": "~3.5.0",
//   "name": "",
//   "escapedName": "",
//   "rawSpec": "~3.5.0",
//   "saveSpec": null,
//   "fetchSpec": "~3.5.0"
// }
// Actual:
// {
//   "type": "tag",
//   "registry": true,
//   "raw": "~3.5.0",
//   "name": "~3.5.0",
//   "escapedName": "~3.5.0",
//   "rawSpec": "",
//   "saveSpec": null,
//   "fetchSpec": "latest"
// }
```

## When

I install a package with npm.

**Example**

```sh
npm i -D typescript@~3.5.0
```

### Current Behavior

npm-package-arg is parsing the spec as `tag`, which I believe it could be thinking the spec is the name of the package (as shown in the **Actual** response below for `name`).

### Expected Behavior

Either an error should be thrown for an invalid argument, or a specifier without package name is parsed correctly.

## References

* npm/cli#636
* npm/arborist#253

**Comment by isaacs** [comment]
Fixed in arborist.
