### ISSUE TITLE
[FEATURE] Support for `workspace:` protocol (Yarn 2)

### ISSUE THREAD

**Issue by tassoevan** [npm/npm-package-arg#57]
# What / Why

Yarn 2 has a special URL protocol for packages that should be resolved within workspaces: https://yarnpkg.com/features/workspaces#workspace-ranges-workspace
Maybe it is [related to a bug on Lerna](https://github.com/lerna/lerna/issues/2564).

## When

* n/a

## Where

* n/a

## How
Try to parse `workspace:xyz`

### Current Behavior

* Throws the error `Unsupported URL Type "workspace:": workspace:xyz`

### Expected Behavior

* Outputs the version described at `xyz/package.json`.

## Who

* n/a

## References

* n/a

**Comment by ljharb** [comment]
I think you may want to file an [RFC](https://github.com/npm/rfcs) for this?

**Comment by isaacs** [comment]
Yes, this needs to be an RFC.  Most of the change will be in https://github.com/npm/arborist (for installing) and https://github.com/npm/libnpmpublish and https://github.com/npm/libnpmpack (for publishing).

**Comment by jrj2211** [comment]
I tried searching the npm/rfcs but couldn't find anything on this topic. Google brings you here when googling workspace protocol for npm. Does anyone have a link to where this is being tracked if it was submitted elsewhere?
