### ISSUE TITLE
[BUG] `npa.Result` wrong filed types

### ISSUE THREAD

**Issue by ArthurKa** [npm/npm-package-arg#58]
# What / Why
`npa.Result` type has fields with `string | null` type declared, but actual types are `string | undefined`.

## When
Every single time.

## Where
In `npa.Result` type.

## How
```ts
import npa from 'npm-package-arg';

const pkg = npa(<packageName>);
console.log(pkg);
```

### Current Behavior
For `<packageName>` as `'node-fetch'` `scope` field value is `undefined` but type is `string | null`.

```ts
Result {
  type: 'tag',
  registry: true,
  where: undefined,
  raw: 'node-fetch',
  name: 'node-fetch',
  escapedName: 'node-fetch',
  scope: undefined,
  rawSpec: '',
  saveSpec: null,
  fetchSpec: 'latest',
  gitRange: undefined,
  gitCommittish: undefined,
  hosted: undefined
}
```

For `<packageName>` as `''` also fields `name` and `escapedName` are `undefined` which is definitely not expected cause of both types `string | null`.

```ts
Result {
  type: 'tag',
  registry: true,
  where: undefined,
  raw: '',
  name: undefined,
  escapedName: undefined,
  scope: undefined,
  rawSpec: '',
  saveSpec: null,
  fetchSpec: 'latest',
  gitRange: undefined,
  gitCommittish: undefined,
  hosted: undefined
}
```

### Steps to Reproduce
Import package, run function, log result, watch on `undefined`s but declared `null`s.

### Expected Behavior
Expect to output declared `null` type or to declare `undefined` instead of `null`.

## Who
* n/a

## References
* n/a

**Comment by ljharb** [comment]
npm-package-arg has no types in it; this should be filed on DefinitelyTyped (for https://www.npmjs.com/package/@types/npm-package-arg) instead.

**Comment by ArthurKa** [comment]
So where is repo for `@types/npm-package-arg`?

**Comment by ljharb** [comment]
Yes. Most packages don’t ship their own types; that repo is the first place to look.

**Comment by ArthurKa** [comment]
Thanks.
