### ISSUE TITLE
[BUG] update from v3 to v4 of `hosted-git-info` in 8.1.2 caused a regression for `git@github.com:user/package-2#semver:^1.0.0`

### ISSUE THREAD

**Issue by JamesHenry** [npm/npm-package-arg#93]
### Is there an existing issue for this?

- [X] I have searched the existing issues

Cross-posting here as this library will need to bump `hosted-git-info` once the issue has been resolved: https://github.com/npm/hosted-git-info/issues/148

**Comment by lukekarrys** [comment]
Confirmed this is fixed by https://github.com/npm/hosted-git-info/pull/152

**Comment by JamesHenry** [comment]
Thank you @lukekarrys, please can you cut a release of `npm-package-arg` which includes the change whenever you get chance?

**Comment by lukekarrys** [comment]
@JamesHenry We are in the process of cutting a major release of `npm-package-arg` (#105) which will include our updated engines and a breaking change around resolving ambiguous specs (https://github.com/npm/npm-package-arg/pull/97). Will including this patch in `v10.0.0` be sufficient for you? If not I can backport to v9 as well.
